### ISSUE TITLE
ERROR: http: panic serving 127.0.0.1:49950: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gidoichi** [gidoichi/ical-converter#80]
Full error message
```console
$ go run main.go
2024/11/04 19:30:27 http: panic serving 127.0.0.1:49950: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go-1.23/src/net/http/server.go:1947 +0xbe
panic({0x832260?, 0xc26e80?})
        /usr/lib/go-1.23/src/runtime/panic.go:785 +0x132
github.com/gidoichi/ical-converter/usecase.(*converter).convertFromTodo(0x8b4ffa?, {{{0xc00055e1e0, 0x3, 0x4}, {0xc00004e300, 0x3, 0x4}}})
        /home/shinichi/ghq/github.com/gidoichi/servers/gcp/ical-converter/ical-converter/usecase/converter.go:51 +0xfe
github.com/gidoichi/ical-converter/usecase.(*converter).Convert(0xc000024820, {0x968340?, 0xc000114450?})
        /home/shinichi/ghq/github.com/gidoichi/servers/gcp/ical-converter/ical-converter/usecase/converter.go:38 +0x1b0
github.com/gidoichi/ical-converter/application.(*convertService).Convert(0x870a20?, {0x968340?, 0xc000114450?})
        /home/shinichi/ghq/github.com/gidoichi/servers/gcp/ical-converter/ical-converter/application/service.go:23 +0x3a
github.com/gidoichi/ical-converter/application.(*Server).ServeHTTP(0xc00004edc0, {0x7f1cae37c068, 0xc00013c140}, 0xc000144000)
        /home/shinichi/ghq/github.com/gidoichi/servers/gcp/ical-converter/ical-converter/application/server.go:105 +0x329
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x96b648?, 0xc000152000?}, 0xc000144000)
        /home/shinichi/go/pkg/mod/github.com/prometheus/client_golang@v1.20.4/prometheus/promhttp/instrument_server.go:147 +0xc3
net/http.HandlerFunc.ServeHTTP(0xc0000d01c0?, {0x96b648?, 0xc000152000?}, 0x67d536?)
        /usr/lib/go-1.23/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x468ed9?, {0x96b648, 0xc000152000}, 0xc000144000)
        /usr/lib/go-1.23/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc000114300?}, {0x96b648?, 0xc000152000?}, 0x6?)
        /usr/lib/go-1.23/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00013e000, {0x96bf28, 0xc000114210})
        /usr/lib/go-1.23/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 13
        /usr/lib/go-1.23/src/net/http/server.go:3360 +0x485
```

**Comment by gidoichi** [comment]
iCalendar exposed by Nextcloud [v30.0.1](https://github.com/nextcloud/server/releases/tag/v30.0.1)
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Home
X-APPLE-CALENDAR-COLOR:#3289d2FF
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Asia/Tokyo
TZURL:http://tzurl.org/zoneinfo/Asia/Tokyo
X-LIC-LOCATION:Asia/Tokyo
BEGIN:STANDARD
TZOFFSETFROM:+091859
TZOFFSETTO:+0900
TZNAME:JST
DTSTART:18880101T001859
RDATE:18880101T001859
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+1000
TZOFFSETTO:+0900
TZNAME:JST
DTSTART:19480912T010000
RDATE:19480912T010000
RDATE:19490911T010000
RDATE:19500910T010000
RDATE:19510909T010000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0900
TZOFFSETTO:+1000
TZNAME:JDT
DTSTART:19480501T235959
RDATE:19480501T235959
RDATE:19490402T235959
RDATE:19500506T235959
RDATE:19510505T235959
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTODO
...
```

**Comment by gidoichi** [comment]
```console
$ git diff
diff --git a/usecase/converter.go b/usecase/converter.go
index 92584a2..ac90b57 100644
--- a/usecase/converter.go
+++ b/usecase/converter.go
@@ -3,6 +3,7 @@ package usecase
 
 import (
        "fmt"
+       "log"
        "reflect"
 
        ical "github.com/arran4/golang-ical"
@@ -48,6 +49,10 @@ func (c *converter) Convert(source DataSource) (converted *ical.Calendar, err er
 
 func (c *converter) convertFromTodo(todo ical.VTodo) *ical.VEvent {
        id := todo.GetProperty(ical.ComponentPropertyUniqueId)
+       if id == nil {
+               log.Printf("todo: %+v", todo)
+               log.Printf("todo.Properties: %+v", todo.Properties)
+       }
        event := ical.NewEvent(id.Value)
 
        for _, prop := range todo.UnknownPropertiesIANAProperties() {

$ go run main.go
...
2024/11/04 19:45:02 todo: {ComponentBase:{Properties:[{BaseProperty:{IANAToken:TZID ICalParameters:map[] Value:Asia/Tokyo}} {BaseProperty:{IANAToken:TZURL ICalParameters:map[] Value:http://tzurl.org/zoneinfo/Asia/Tokyo}} {BaseProperty:{IANAToken:X-LIC-LOCATION ICalParameters:map[] Value:Asia/Tokyo}}] Components:[0xc000444630 0xc000444a50 0xc000444e70]}}
2024/11/04 19:45:02 todo.Properties: [{BaseProperty:{IANAToken:TZID ICalParameters:map[] Value:Asia/Tokyo}} {BaseProperty:{IANAToken:TZURL ICalParameters:map[] Value:http://tzurl.org/zoneinfo/Asia/Tokyo}} {BaseProperty:{IANAToken:X-LIC-LOCATION ICalParameters:map[] Value:Asia/Tokyo}}]
2024/11/04 19:45:02 http: panic serving 127.0.0.1:55984: runtime error: invalid memory address or nil pointer dereference
goroutine 42 [running]:
...
```
